services:
  backend:
    build:
      context: ./apps/server
    ports:
      - "3000:3000"
    env_file:
      - ./apps/server/.env
    restart: always
    networks:
      - chatassistant
    command: >
      sh -c "npx prisma generate && npm run start"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: /api
    ports:
      - "8080:8080"
    restart: always
    dns:
      - 8.8.8.8
      - 9.9.9.9
    environment:
      - VITE_BACKEND_URL=/api
    networks:
      - chatassistant
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/Login || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - chatassistant
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80/Login || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  chatassistant:
    driver: bridge
